name: Build docker image and run docfx
on:
  pull_request_target:
    branches: [ main, feature/*, hotfix/* ]
  push:
    branches: [ main, feature/*, hotfix/* ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    environment: ci
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
    steps:

      # Checkout
      - uses: actions/checkout@v4

      # Build docker image
      - run:
          docker build ./ -t docfx
    
      # Output docker image size
      - run: |
          dotnet nuget locals all --list
          docker images

      # Run docfx command
      - run: >-
          docker run
          --name docfx
          --rm
          --volume ${{ github.workspace }}:/opt/prj
          docfx docs/docfx.json
    
      # Upload site artifacts
      - uses: actions/upload-artifact@v4
        if: ${{ matrix.os == 'ubuntu-latest' }}
        with:
          name: site
          path: docs/_site/*
